setup:
  channels: &setup_channels
    - conda-forge
    - default
  dependencies: &setup_dependencies
    - python
    - setuptools
    - numpy

production:
  channels: &production_channels
    - *setup_channels
  dependencies: &production_dependencies
    - python
    - pint
    - openmm

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pip
    - pytest-cov
    - codecov
    - unyt

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - myst-nb
    - unyt

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - jupyterlab
    - pyyaml

conda-build:
  channels:
    - *setup_channels
  dependencies:
    - *setup_dependencies
    - anaconda-client
    - conda-build

