package:
  name: pyunitwizard
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - versioneer

  run:
    - python
    - numpy
    - pint

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful methods to work with quantities
  dev_url: https://github.com/uibcdf/PyUnitWizard
  doc_url: https://uibcdf.org/PyUnitWizard

